ALTER TABLE topics ADD FOREIGN KEY (topic_cat) REFERENCES categories (cat_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE topics ADD FOREIGN KEY (topic_by) REFERENCES users (user_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE posts ADD FOREIGN KEY (post_topic) REFERENCES topics (topic_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE posts ADD FOREIGN KEY (post_by) REFERENCES users (user_id) ON DELETE RESTRICT ON UPDATE CASCADE;